networks:
  audrey:
services:
  audrey-fast-api:
    # build: .
    image: audre-fastapi:1.0
    restart: always
    # privileged: true
    # user: root
    # volumes:
    # - ./certs:/certs/client
    # - ./data:/var/jenkins_home
    ports:
    - 80:80
    # environment:
    #   DOCKER_HOST: tcp://docker:2376
    #   DOCKER_CERT_PATH: /certs/client
    #   DOCKER_TLS_VERIFY: 1
    networks:
      - audrey
